# Generated by Django 4.0.6 on 2023-12-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questions_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='name',
            new_name='question_text',
        ),
    ]
