# Generated by Django 5.0 on 2023-12-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_auto_20200908_0339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
