# Generated by Django 5.0 on 2023-12-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0005_alter_ad_id_alter_comment_id_alter_fav_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
